#!/bin/sh
/root/Desktop/crf_project/crf_project/CRF++-0.58/crf_learn -c 10.0 /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/template/agent_template /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/pre_data/first_event_agent.txt /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/model/event_agent_model_1110
/root/Desktop/crf_project/crf_project/CRF++-0.58/crf_test  -m /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/model/event_agent_model_1110 /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/pre_data/event_pre_agent_E.txt > /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/output/event_agent_1110.output

/root/Desktop/crf_project/crf_project/CRF++-0.58/crf_learn -c 10.0 /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/template/agent_template /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/pre_data/second_event_agent.txt /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/model/event_agent_model_2110
/root/Desktop/crf_project/crf_project/CRF++-0.58/crf_test  -m /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/model/event_agent_model_2110 /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/pre_data/event_pre_agent_A.txt > /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/output/event_agent_2110.output

/root/Desktop/crf_project/crf_project/CRF++-0.58/crf_learn -c 10.0 /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/template/agent_template /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/pre_data/third_event_agent.txt /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/model/event_agent_model_3110
/root/Desktop/crf_project/crf_project/CRF++-0.58/crf_test  -m /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/model/event_agent_model_3110 /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/pre_data/event_pre_agent_B.txt > /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/output/event_agent_3110.output

/root/Desktop/crf_project/crf_project/CRF++-0.58/crf_learn -c 10.0 /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/template/agent_template /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/pre_data/four_event_agent.txt /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/model/event_agent_model_4110
/root/Desktop/crf_project/crf_project/CRF++-0.58/crf_test  -m /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/model/event_agent_model_4110 /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/pre_data/event_pre_agent_C.txt > /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/output/event_agent_4110.output

/root/Desktop/crf_project/crf_project/CRF++-0.58/crf_learn -c 10.0 /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/template/agent_template /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/pre_data/five_event_agent.txt /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/model/event_agent_model_5110
/root/Desktop/crf_project/crf_project/CRF++-0.58/crf_test  -m /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/model/event_agent_model_5110 /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/pre_data/event_pre_agent_D.txt > /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/output/event_agent_5110.output


/root/Desktop/crf_project/crf_project/CRF++-0.58/crf_learn -c 10.0 /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/template/operation_template /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/pre_data/first_event_operation.txt /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/model/event_operation_model_1110
/root/Desktop/crf_project/crf_project/CRF++-0.58/crf_test  -m /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/model/event_operation_model_1110 /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/pre_data/event_pre_operation_E.txt > /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/output/event_operation_1110.output

/root/Desktop/crf_project/crf_project/CRF++-0.58/crf_learn -c 10.0 /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/template/operation_template /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/pre_data/second_event_operation.txt /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/model/event_operation_model_2110
/root/Desktop/crf_project/crf_project/CRF++-0.58/crf_test  -m /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/model/event_operation_model_2110 /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/pre_data/event_pre_operation_A.txt > /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/output/event_operation_2110.output

/root/Desktop/crf_project/crf_project/CRF++-0.58/crf_learn -c 10.0 /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/template/operation_template /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/pre_data/third_event_operation.txt /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/model/event_operation_model_3110
/root/Desktop/crf_project/crf_project/CRF++-0.58/crf_test  -m /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/model/event_operation_model_3110 /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/pre_data/event_pre_operation_B.txt > /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/output/event_operation_3110.output

/root/Desktop/crf_project/crf_project/CRF++-0.58/crf_learn -c 10.0 /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/template/operation_template /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/pre_data/four_event_operation.txt /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/model/event_operation_model_4110
/root/Desktop/crf_project/crf_project/CRF++-0.58/crf_test  -m /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/model/event_operation_model_4110 /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/pre_data/event_pre_operation_C.txt > /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/output/event_operation_4110.output

/root/Desktop/crf_project/crf_project/CRF++-0.58/crf_learn -c 10.0 /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/template/operation_template /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/pre_data/five_event_operation.txt /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/model/event_operation_model_5110
/root/Desktop/crf_project/crf_project/CRF++-0.58/crf_test  -m /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/model/event_operation_model_5110 /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/pre_data/event_pre_operation_D.txt > /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/output/event_operation_5110.output


/root/Desktop/crf_project/crf_project/CRF++-0.58/crf_learn -c 10.0 /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/template/input_template /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/pre_data/first_event_input.txt /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/model/event_input_model_1110
/root/Desktop/crf_project/crf_project/CRF++-0.58/crf_test  -m /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/model/event_input_model_1110 /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/pre_data/event_pre_input_E.txt > /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/output/event_input_1110.output

/root/Desktop/crf_project/crf_project/CRF++-0.58/crf_learn -c 10.0 /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/template/input_template /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/pre_data/second_event_input.txt /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/model/event_input_model_2110
/root/Desktop/crf_project/crf_project/CRF++-0.58/crf_test  -m /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/model/event_input_model_2110 /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/pre_data/event_pre_input_A.txt > /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/output/event_input_2110.output

/root/Desktop/crf_project/crf_project/CRF++-0.58/crf_learn -c 10.0 /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/template/input_template /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/pre_data/third_event_input.txt /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/model/event_input_model_3110
/root/Desktop/crf_project/crf_project/CRF++-0.58/crf_test  -m /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/model/event_input_model_3110 /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/pre_data/event_pre_input_B.txt > /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/output/event_input_3110.output

/root/Desktop/crf_project/crf_project/CRF++-0.58/crf_learn -c 10.0 /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/template/input_template /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/pre_data/four_event_input.txt /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/model/event_input_model_4110
/root/Desktop/crf_project/crf_project/CRF++-0.58/crf_test  -m /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/model/event_input_model_4110 /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/pre_data/event_pre_input_C.txt > /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/output/event_input_4110.output

/root/Desktop/crf_project/crf_project/CRF++-0.58/crf_learn -c 10.0 /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/template/input_template /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/pre_data/five_event_input.txt /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/model/event_input_model_5110
/root/Desktop/crf_project/crf_project/CRF++-0.58/crf_test  -m /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/model/event_input_model_5110 /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/pre_data/event_pre_input_D.txt > /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/output/event_input_5110.output

/root/Desktop/crf_project/crf_project/CRF++-0.58/crf_learn -c 10.0 /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/template/output_template /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/pre_data/first_event_output.txt /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/model/event_output_model_1110
/root/Desktop/crf_project/crf_project/CRF++-0.58/crf_test  -m /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/model/event_output_model_1110 /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/pre_data/event_pre_output_E.txt > /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/output/event_output_1110.output

/root/Desktop/crf_project/crf_project/CRF++-0.58/crf_learn -c 10.0 /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/template/output_template /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/pre_data/second_event_output.txt /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/model/event_output_model_2110
/root/Desktop/crf_project/crf_project/CRF++-0.58/crf_test  -m /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/model/event_output_model_2110 /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/pre_data/event_pre_output_A.txt > /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/output/event_output_2110.output

/root/Desktop/crf_project/crf_project/CRF++-0.58/crf_learn -c 10.0 /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/template/output_template /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/pre_data/third_event_output.txt /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/model/event_output_model_3110
/root/Desktop/crf_project/crf_project/CRF++-0.58/crf_test  -m /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/model/event_output_model_3110 /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/pre_data/event_pre_output_B.txt > /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/output/event_output_3110.output

/root/Desktop/crf_project/crf_project/CRF++-0.58/crf_learn -c 10.0 /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/template/output_template /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/pre_data/four_event_output.txt /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/model/event_output_model_4110
/root/Desktop/crf_project/crf_project/CRF++-0.58/crf_test  -m /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/model/event_output_model_4110 /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/pre_data/event_pre_output_C.txt > /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/output/event_output_4110.output

/root/Desktop/crf_project/crf_project/CRF++-0.58/crf_learn -c 10.0 /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/template/output_template /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/pre_data/five_event_output.txt /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/model/event_output_model_5110
/root/Desktop/crf_project/crf_project/CRF++-0.58/crf_test  -m /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/model/event_output_model_5110 /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/pre_data/event_pre_output_D.txt > /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/output/event_output_5110.output

/root/Desktop/crf_project/crf_project/CRF++-0.58/crf_learn -c 10.0 /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/template/restriction_template /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/pre_data/first_event_restriction.txt /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/model/event_restriction_model_1110
/root/Desktop/crf_project/crf_project/CRF++-0.58/crf_test  -m /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/model/event_restriction_model_1110 /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/pre_data/event_pre_restriction_E.txt > /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/output/event_restriction_1110.output

/root/Desktop/crf_project/crf_project/CRF++-0.58/crf_learn -c 10.0 /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/template/restriction_template /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/pre_data/second_event_restriction.txt /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/model/event_restriction_model_2110
/root/Desktop/crf_project/crf_project/CRF++-0.58/crf_test  -m /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/model/event_restriction_model_2110 /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/pre_data/event_pre_restriction_A.txt > /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/output/event_restriction_2110.output

/root/Desktop/crf_project/crf_project/CRF++-0.58/crf_learn -c 10.0 /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/template/restriction_template /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/pre_data/third_event_restriction.txt /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/model/event_restriction_model_3110
/root/Desktop/crf_project/crf_project/CRF++-0.58/crf_test  -m /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/model/event_restriction_model_3110 /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/pre_data/event_pre_restriction_B.txt > /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/output/event_restriction_3110.output

/root/Desktop/crf_project/crf_project/CRF++-0.58/crf_learn -c 10.0 /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/template/restriction_template /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/pre_data/four_event_restriction.txt /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/model/event_restriction_model_4110
/root/Desktop/crf_project/crf_project/CRF++-0.58/crf_test  -m /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/model/event_restriction_model_4110 /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/pre_data/event_pre_restriction_C.txt > /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/output/event_restriction_4110.output

/root/Desktop/crf_project/crf_project/CRF++-0.58/crf_learn -c 10.0 /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/template/restriction_template /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/pre_data/five_event_restriction.txt /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/model/event_restriction_model_5110
/root/Desktop/crf_project/crf_project/CRF++-0.58/crf_test  -m /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/model/event_restriction_model_5110 /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/pre_data/event_pre_restriction_D.txt > /root/Desktop/crf_project/crf_project/CRF++-0.58/example/exp/output/event_restriction_5110.output





